global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/alert_rules.yml

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      # Ubah ke 9090 karena ini dibaca dari dalam container itu sendiri
      - targets: ['localhost:9090'] 

  - job_name: 'model_exporter'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['exporter:5880']