services:
  exporter:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5880:5880'
      - '5881:5881'
    #volumes:
      # Mount the mlruns folder directly to /mlruns inside the container
      #- ../Membangun_model/mlruns:/mlruns

  prometheus:
    image: prom/prometheus:latest
    ports:
      # Format: 'Port_Host:Port_Container'
      # Anda bisa akses dari luar lewat localhost:5800, 
      # lalu Docker akan meneruskannya ke port 9090 di dalam.
      - '5800:9090' 
    volumes:
      - ./2.prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./alert_rules.yml:/etc/prometheus/alert_rules.yml:ro
    depends_on:
      - exporter

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SECURITY_ADMIN_USER=admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
      - GF_AUTH_DISABLE_LOGIN_FORM=false
    ports:
      # Akses Grafana via localhost:5890, diteruskan ke port internal 3000
      - '5890:3000' 
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - prometheus
