version: '3.8'
services:
  exporter:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5880:5880'
      - '5881:5881'
    volumes:
      # Mount the mlruns folder directly to /mlruns inside the container
      - ../Membangun_model/mlruns:/mlruns

  prometheus:
    image: prom/prometheus:latest
    ports:
      - '5800:5800'
    volumes:
      - ./2.prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./alert_rules.yml:/etc/prometheus/alert_rules.yml:ro
    depends_on:
      - exporter

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SECURITY_ADMIN_USER=admin
    ports:
      - '5890:5890'
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - prometheus
